project:
  type: website

website:
  title: "依然在路上"
  site-url: yiranyiran.netlify.app
  description: "This is Yiran's personal blog"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/denisezh
format:
  html:
    theme: 
      light: morph
      dark: cyborg
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.7

editor: visual

