project:
  type: website

website:
  title: "依然在路上"
  site-url: yiranyiran.netlify.app
  description: "This is Yiran's personal blog"
  page-footer:
    left: |
      Website made with [Quarto](https://quarto.org/), by Denise Yiran Zheng.\ 
      License: [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)\
      Opinions are my own and do not represent my employer
  navbar:
    right:
      - text: 聞思修blog
        href: blog.qmd
      - icon: github
        href: https://github.com/denisezh/Yiran-blog/
format:
  html:
    theme:
      light: morph
      dark: cyborg
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.7

editor: visual

