project:
  type: website

website:
  title: "Yiran-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: morph
      dark: cyborg
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.7

editor: visual

