---
title: "how I built this blog"
date: '2025-05-03'
categories: ['R']
description: 'In this post, I include the resources I utilized to build this blog'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

## how to create a free blog with Quarto?

Welcome to my new blog. Since I finished my doctoral degree, I haven't been using R as much. So to keep using this skill, I thought I would create a blog using R in a way that is free and open-source. After some searches, I found that Quarto would be the best option. 

### resources/guides I followed to create this blog:

[Creating a blog with Quarto in 10 steps](https://beamilz.com/posts/2022-06-05-creating-a-blog-with-quarto/en/#deploy-with-netlify) by Beatriz Milz, PhD

[Creating a blog documentation](https://quarto.org/docs/websites/website-blog.html) by Quarto

[The ultimate guide to starting a Quarto blog](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.html#build-your-own-landing-page) by Albert Rapp, PhD

[Building a blog with Quarto](https://ivelasq.quarto.pub/building-a-blog-with-quarto/) by Isabella Velásquez

It is worth checking out the Github pages for each of the websites listed above as they contain the codes that can give you ideas on how to format your blog.

### some blogs to check out for insiprations

[Andreas Handel, PhD's blog](https://www.andreashandel.com/)

This is not a blog made using Quarto but a blog that gave me inspiration to the style of blog I want to create and that I find aesthetically pleasing: 
[jinjin's blog](https://www.jinjinchen.com/)

