---
title: "publications"
date: '2025-04-27'
categories: ['writing']
description: 'In this post, I list my research work and op-ed essays'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# publications and op-ed

## 2025

[Not just someone’s daughter, wife, or mother](https://1990institute.salsalabs.org/1990newsletter_vol5_issue3)

**Zheng, D.Y.**, Beloborodova, P., Brown, K.W., & Arch, J. (2025). Emotional benefits of mindfulness. In Brown, K.W., Creswell, J.D., & Ryan, R.M (Eds.). [*Handbook of mindfulness: Theory, research, and practice, 2e*](https://www.guilford.com/books/Handbook-of-Mindfulness/Brown-Creswell-Ryan/9781462557004). New York: Guilford.

[China’s fur trade and its position in the global fur industry: Update 2022/2023](https://www.actasia.org/wp-content/uploads/2025/02/Fur-Report_2024_Digital_FAR.pdf)

[China’s growing influence on the world of trade](https://1990institute.salsalabs.org/1990newsletter_vol4_issue11_copy1)

## 2024

Roy, E., Jaeger, B., Evans, A. M., Turetsky, K. M., O'Shea, B. A., Petersen, M. B., Singh, B., Correll, J., **Zheng, D. Y.**, Brown, K. W., Kirgios, E. L., Chang, L. W., Chang, E. H., Steele, J. R., Sebastien, J., Sedgewick, J. R., Hackney, A., Cook, R., Yang, X., . . . Axt, J. R. (2024). A contest study to reduce attractiveness-based discrimination in social judgment. *Journal of Personality and Social Psychology*. Advance online publication. <https://doi.org/10.1037/pspa0000414>

[Have recent U.S.-China talks translated into action?](https://1990institute.salsalabs.org/1990newsletter_vol4_issue11)

[Taiwan and the chips that power our world](https://1990institute.salsalabs.org/1990newsletter_vol4_issue9)

[Reflections on the 1990 Institute’s Teachers Workshop on U.S.-China Relations](https://1990institute.salsalabs.org/1990newsletter_vol4_issue7)

[Bridging differences through contact](https://1990institute.salsalabs.org/1990newsletter_vol4_issue5)

**Zheng, D.**, (2024). \[Effects of Mindfulness Training on Prosocial Responses in Intergroup Relations: A Pilot Randomized Controlled Trial\](http://proxy.library.vcu.edu/login?url=https://www.proquest.com/dissertations-theses/effects-mindfulness-training-on-prosocial/docview/3067632825/se-2?accountid=14780) (Publication No. 31239514) \[Doctoral dissertation, Virginia Commonwealth University\]. ProQuest Dissertations and Theses Global.

[Where Do the Fresh Graduates Go?](https://1990institute.salsalabs.org/1990newsletter_vol4_issue3)

## 2023

**Zheng, D.**, Berry, D. R., & Brown, K. W. (2023). Effects of brief mindfulness meditation and compassion meditation on parochial empathy and prosocial behavior toward ethnic out-group members. *Mindfulness*. <https://doi.org/10.1007/s12671-023-02100-z>

## 2022

[How to Take on a Pipeline (and Win)](https://blog.ucsusa.org/science-blogger/how-to-take-on-a-pipeline-and-win/)

**Zheng, D.** (2022). [The role of mindfulness and compassion in parochial empathy and prosocial behavior toward out-groups](https://scholarscompass.vcu.edu/etd/7004/) (Publication No. 29214163) \[Master’s thesis, Virginia Commonwealth University\]. ProQuest Dissertations and Theses Global.
