---
title: "藏語基础入门 intro to Tibetan: for beginners"
date: '2025-07-10'
categories: ['Tibetan']
description: 'In this post, I documented how I learn Tibetan in the first month. Hopefully by following this schedule for a month, you could also read (almost) all Tibetan words by the end of this post.'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# 藏語學習

今年2025四月開始學習藏語，這裏紀錄我所用到的學習資源和對我來説有用的學習方法。我并不是光靠自學，而是同時有去上課，聼老師的發音和得到糾正是非常重要的。在課下，我會每天發一到三個小時用以下的資源復習并且學習我在課上沒學到的。

All the resources listed below can be used by English speakers to learn Tibetan. For some of them, the teachers teach in Chinese, while some teaches in Tibetan or English (marked with asterisk\*). I see these resources as supplemental or for self-study in addition attending in-person classes because it is important to see and hear directly how the teachers pronounce each word and get feedback.

Please see the other blog post called "*Tibetan studying resources*" for additional materials such as dictionaries to use.

## 學習表 study schedule

### week 1: 30个輔音字母 \| Tibetan alphabet (30 consonants)

要多聼每個字母的發音，邊聽邊大聲跟讀（一定要大聲，這樣容易記住也可以聽聽自己的發音對不對）

剛開始會感覺很難，特別是ང的發音，對我最有幫助的這個字母的發音解釋是 "sing" 裏面的 "-ng" 音 + a (nga)，多練就可以發對音了！

一般外國人學藏語是直接學烏金字體，但是藏族小孩一開始是學烏梅字體。我的阿尼朋友們跟我說一般她們寫字都是用烏梅，寫筆記比烏金快。我一開始在寺裡學藏語，老師是教烏梅，然後同時另外自學烏金。我覺得一開始兩個一起學比較有效。

學烏梅可以參考[這本書](https://bodyiglobjong.com/%E0%BD%A6%E0%BE%94%E0%BD%BC%E0%BD%93%E0%BC%8B%E0%BD%A0%E0%BD%82%E0%BE%B2%E0%BD%BC%E0%BD%A0%E0%BD%B2%E0%BC%8B%E0%BD%A6%E0%BE%B3%E0%BD%BC%E0%BD%96%E0%BC%8B%E0%BD%91%E0%BD%BA%E0%BD%96%E0%BC%8D-3/)

[烏梅字體筆畫練習](https://issuu.com/doewebmaster/docs/seru_yigzuag_2017_1_)

我每天一般一半時間練習烏梅，一半練習烏金。學藏語的頭兩個星期我會默寫這兩個字體的30字母，把它們都背下來，然後陸續開始學上加字，後加字等等。對我來說烏梅的上加字和下加字比烏金複雜，我容易搞混（比如說不知道是yata還是rata)，學的時候跟烏金對比會比較好認。

第一個星期我學習用的資源：

1)  丹增南卓仁波切教的[第 1 堂｜基礎藏語班](https://youtu.be/8_wjc-9urtk?si=450FdaXan1huZGMG)

2)  寫字母 (script writing)

<!-- -->

a)  [視頻\*](https://youtu.be/vl0WoxLsaRg)

b)  [網站\*](https://web.archive.org/web/20130128174741/https://sites.google.com/site/chrisfynn2/home/tibetanscriptfonts/howtowritethetibetanscript)

<!-- -->

3)  [基本拼音](https://buddhism.lib.ntu.edu.tw/lesson/tibet/lesson_tibet02.jsp#4) - 臺大佛學數位圖書館

4)  每天看一個藏語視頻 — [丹達讀逗4分鐘藏語教室](https://youtube.com/playlist?list=PLB3W-1GsVMGDLvdC0l8-cZPbh7blBhU6c&si=47OQF_s6UB0HoDlB) (can also be used for English speakers)

[Unit 1: The alphabet](https://tibetanlanguage.school/learn/standard-tibetan/unit-1/) \| Tibetan Language School

### week 2: 元音符號 \| 4 vowels

繼續多多練習輔音字母，這個星期也開始學習四個元音符號

1)  丹增南卓仁波切教的[第二堂基礎藏語班](https://youtu.be/Gzv5tLOQTWc?si=63RcPU6YcCp17Crb)

2)  藏語[四元音 vowels\*](https://youtube.com/playlist?list=PLq5rrkU-Q2F05_BEGkVlIgOJeYyyuXZ48&si=g9fPVuAmIvMZb9gb)

3)  數字1-10 [丹達讀逗 4分鐘藏語教室 數字篇-1 Number 1-10](https://youtu.be/JKK6Wnfl5OY?si=ceQnPPeucWS-D_w4)

[數字兒歌](https://www.youtube.com/watch?v=_YNLWeBIE5Y&ab_channel=SherigVideo)

### week 3: 上加字，下加字 \| superscript, subscript

如果過去兩個星期堅持每天都堅持背誦和默寫30字母的話，這個星期應該所有字母都記的差不多了，這個星期可以繼續複習四元音的發音，和開始學上加字和下加字

讀藏語有點像在做數學的加減乘除，所以**基礎要打好**，記住30個字母以及它們的正確發音是繼續學以下部分的前提，慢慢的我們就可以讀所有看到的藏語字

1）[四元音複習\*](https://youtu.be/V6YHceLgwqg?si=MsdtkOCVr98U64ql)

2)  [上加字\*](https://buddhism.lib.ntu.edu.tw/test_teach/BASIC4-0.HTM) 上加字是先讀上加字再讀輔音字母，最後讀整個字的音：ང ra + ཀ ga + ད tha = རྐ ga

3)  [下加字\*](https://youtu.be/cg3EXz8ocvQ?si=UFi6BTgx7qDzenDc) 下加字是先讀輔音字母的音，再讀下加字，最後讀整個字：ཀ ga + ང ra + ད tha = ཀྲ dra

### week 4: 字母復習，後加字 \| reviews, suffix

1)  丹增南卓仁波切 [第 3 堂｜基礎藏語班](https://youtu.be/7MAN3ESqs_I?si=d6hGfnvupIt98a3h)

2)  Sambhota Schools\*: [ཀ字母單詞 #1](https://youtu.be/3nrUcLhpEA8?si=XSY-KI2I_GJs_G2y) [ཅ字母單詞 #2](https://youtu.be/mIdGktdJpro?si=D8fOz9_-_AVOpLxt) [ཏ字母單詞 #3](https://youtu.be/YoRvNvhJZ9k?si=fKfMhwDpnMr8mDAO) [པ字母單詞 #4](https://youtu.be/wkvNilDHrcc?si=_unEJV-NzHe1GjUZ) [ཙ字母單詞 #5](https://youtu.be/xt34bL8prso?si=FBCUVGOZ4NzHHHcE) [ཞ字母單詞 #6](https://youtu.be/qww-PVEUklE?si=F7OP1tkk5A4OhnxK)

[ར字母單詞 #7](https://youtu.be/kjhMNQY2oOk?si=30QEfUriokytTTWv)

[ཧ字母單詞 #8](https://youtu.be/NdyuybRAEII?si=vdGaoQa6hpCkq_WP)

3)  下加字復習 Subscript\*

[ཡ་བཏགས་yatag](https://youtu.be/3EkW8a0Z6BA?si=vPmsZs5sm-UMcrnw)

[ར་བཏགས་ratag](https://youtu.be/cQ9vXCJ5YNI?si=9mmCndzsvghmCImW)

[ལ་བཏགས་latag](https://youtu.be/_cVmaJnr0Ko?si=0kyZXIesZrliVmti)

[ཝ་ཟུར་wasur](https://youtu.be/wra0A3szfps?si=fRv-4xwU97HQrNEM)

4)  [རྗེས་འཇུག་བཅུ།怎麼讀有後加字的詞 \| how to pronounce words with suffix\*](https://youtu.be/C_gfM9jVGGM?si=f0qwkv4g1xtFaZLK)

### Conclusion of first month: prefix, adjacent letters review, numbers \| 前加字，數字

After one month, it is possible to pronouce almost all the words in Tibetan if we study and practice the alphabet and [adjacent letters](https://tibetanlanguage.school/learn/standard-tibetan/unit-2/) thoroughly. Therefore, it is very important to build this foundation in the first month.

Here is another review of the [stacked letters](https://www.youtube.com/watch?v=QHf2yEq_cvc&ab_channel=BodYigJung) to practice pronounciation.

Some pronounciation notes to keep in mind from [Tibetan Language School](https://tibetanlanguage.school/learn/standard-tibetan/unit-2/): - If you have a single consonant letter with a vowel letter on top (e.g. ལོ་), then the consonant letter is the main letter. - Prefix letters and superscript letters cause some main letters to become voiced (e.g. th turns into “d”, and kh into “g”): འདེབས་ dep སྒོ་ go - prefix letters, ག་ད་བ་མ་འ་, are silent letters with no pronunciation in and of themselves. However, depending on the following main letter, the prefix letter may change the pronunciation of a syllable. - The syllables བ་ and བོ་ are pronounced as “wa” and “wo” respectively when they’re not the first syllable of a word: ཇོ་བོ་ chhowo བྱ་བྲལ་བ་ chha trhälwa

-   when the main letter བ་ is preceded by the suffix letter ད་, the two letters together are pronounced as a high-tone w, and this w may also become silent before the vowel u
-   Most of the time, the suffix letter ད་ is completely silent, the suffix letters ས་ and འ་ are generally silent\
-   when preceding a nasal consonant (i.e. when the following syllable has ང་, ཉ་, ན་ or མ་ as its main letter), the suffix letter ག་ tends to be pronounced like ང་: བདག་མེད་ dangme
-   The suffix letter འ་ must be added to any syllable that has only a prefix letter and a main letter, with no vowel letter
-   the post-suffix letter ས་ cannot occur after the suffix letters ན་, ར་, or ལ་
-   In most two-syllable words the second syllable is pronounced high-tone, even if it would naturally be low-tone. The exception is that in two-syllable verbs, the second syllable is typically pronounced low-tone, even if would naturally be high-tone.
-   Often in three syllable words, the first syllable is treated as one chunk, and the second and third syllables are treated as another chunk.
-   Consonant restoration typically happens when the first syllable of the word is an open syllable, meaning that it ends in a vowel sound. After an open syllable, a silent letter at the beginning of the second syllable has the space to reappear (or be “restored”) in the pronunciation. The restored consonant is generally pronounced as if it were the suffix letter of the first syllable, even though it’s not.

Here are the usual restorations of the five prefix letters: བཅུ་གཅིག་ chukchik (restored “k” from the prefix letter ག་) ཉི་ཤུ་རྩ་དགུ་ nyishu tsargu (restored “r” from the prefix letter ད་) ས་བཀྲ་ saptra (restored “p” from the prefix letter བ་) ཨ་མདོ་ amdo (restored “m” from the prefix letter མ་) དེ་འདྲ་ thendra (restored “n” from the prefix letter འ་)

The restored prefix letter མ་ causes the same kinds of changes as འ་ after both open and closed syllables: གཟའ་མཇུག་ sanjuk ས་མགོ་ sang-go ཡིག་མགོ་ ying-go

[數字 1-100 numbers\*](https://youtu.be/VpvVv397ryU?si=g281NwGs2_HG7pWq)

[數字 1-10](https://youtu.be/JKK6Wnfl5OY?si=VlMq1F92adOm1K0y)

[數字11-30](https://youtu.be/X8UX2-Xm1wQ?si=sZgWuaYClFpVV4Iy)

[數字31-60](https://youtu.be/jv4YPO7nsEo?si=-la37OaA7P0MZ-q3)

[數字61-100](https://youtu.be/ENssuPtURjM?si=X1UrC9xsL_cIIJfl)

[數字規則 number rules](https://youtu.be/3cdYBPTBAc4?si=xlkQWXkyzGGQY_Oy)

Now, we can start learning grammar and reading text. I will create another post for intermediate Tibetan.
