---
title: "社會心理學 social psychology and how I graduated with a PhD in 4 years"
date: '2025-05-22'
categories: ['psychology']
description: 'In this post, I write about why and how I became a social psychologist'
execute: 
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

# 爲什麽讀博？爲什麽是社會心理學？

## 高中種下的種子

我從高中就開始對心理學感興趣，修心理學課的時候我頭一次開始向内看，我學到的知識然我更加瞭解自己和理解她人與人類所共享的許多相似的心理需求。

年少時沒預想到我會一直讀完博士，拿到學位后終於可以稱自己為社會心理學家，所以算完成了我的一大夢想。大二的時候我接觸到了正念冥想，這變成了我的主要研究，同時，我最想要研究的是人們如何能夠無分別心的對外人有同理心并且願幫助TA人。

## 社會心理學和人們對科學 （還有心理學）的誤解

就像一個系裏有很多學科，心理學也分幾個不同的方面。大部人想到心理學一般是臨床心理學方面或者心理咨詢。**社會心理學** 是研究人們的思想，感情，和行爲是怎麽被TA人所影響的。當人們聽到我是學心理學的，很多人會問 "那你知道我現在在想什麽嗎？” 答案是不能。

我覺得大衆很容易忽視心理學的科學部分。心理學是**社會科學**，它的基礎是科學的思想和研究。這特別是社會心理學最吸引我的一部分，我的教授們常說任何人們感興趣的東西，社會科學家應該都有研究過（或可以去研究）。

什麽是*科學的思想*?

對我來説，好的科學家應該以開放的心態去學習，探索未知，和質疑已知。科學是不停更新的，主流理論 （theory) 也有可能被新的研究成果推翻，我們需要靈活的去持續更新自己的認知。所以學心理學并不能一勞永逸。

# why a PhD in social psychology？

## resources I found useful

During the first two years of grad school, I spent some time diving into research such as "how to work efficiently" as productivity was valued highly in grad school. I found one key to "efficiency," and by that I meant working on what I need to get done for the degree while still preserving enough time for doing things that sustain me. In grad school, one can easily revolve one's life to center around research. Therefore, it is important to set a boundary on work time. I find *time blocking* especially useful to structure my work schedule for the weekdays. At the beginning of each semester, I will go over the syllabus for each class, and put in the deadlines for exams and assignments into the calendar. Additionally, I will also block out time slots preceding those deadlines of what I think approximately will take me to complete to assignment or studies. I will also put into calendar major research phases such as study design and data analysis. Once a week (I did Friday afternoon), I will take about 10-15 minutes to plan out what I will work on for the following week. I will literally "block" out different time slots on Google Calendar and color code them based on the type of work they are (e.g., dark blue for meditation sessions, yellow for classes, gray for meetings, dark green for paid work, red for deadlines). This way, I have a clear idea of what I need to do for that day. This planning also ensures that I finished all the work on time and usually a bit earlier than the deadline. Of course, the schedule can be modified through out the day as I went about it but outlining it ahead of time eliminates some of the time of feeling lost and wondering what I need to do.

The first two years of grad school, I was working almost everyday, which felt like I was always working. This did not work since I felt burnt out every summer break. Then, I decided to keep the weekend free for only doing things with friends and other activities I found relaxing.

Meditation was a crucial part of how I was able to remain calm through the ups and downs of PhD. I learned how to practice mindfulness mediation when I was sophomore in college. When grad school started, I realized it was important for me to keep a consistent practice because I felt a heightened level of stress that I never felt before. So I usually meditate each day for around 20 to 40 minutes. I also goes to a in person group meditation once a week as I find I can meditation deeper sometimes in a group setting and it is nice to connect with other people who is also into meditation and Buddhism.

## tools I used

I used Obsidian for note taking as it is great for linking notes and ideas. I also use Google Keep a lot for taking quick notes of the ideas I have.

## what to do with a PhD and different ways of life

For me, I never intended to stay in academia and become a professor so I go on a quite nontraditional path during and post-grad school. One of the main reasons why I chose to specialize in social psychology is because I see that it is relevant for everyone and for our daily lives. I want to be able to apply what I learned to have the most impact I could. It makes more sense for me to consider options that is more in the applied field where my work can possibly have influence on education and policy. One event that changed how I proceed with grad school is when I met with two professors at VCU to discuss my interests and they commented that if you want to take the nontraditional route then you cannot follow what everyone else is doing (to become a professor). Thus, I started exploring groups that share my values and vision. Given my research expertise in intergroup relations and my own experience as a Chinese American, I started working with a non-profit org that focuses on promoting the education of Asian American history and constructive US-China relations. I have continued this work along with my wish to alleviate suffering that farmed animals experience, which I worked with another non-profit to promote the education of compassionate and sustainable behavior toward other living beings and the environment.
